services:
  - type: web
    name: video-moderation-app
    env: python
    runtime: python-3.9
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app --workers=1 --threads=4 --timeout=600 --bind=0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
    autoDeploy: true
    buildFilter:
      paths:
        - ./*.py
        - ./templates/*
        - ./models/*
        - ./static/*
        - requirements.txt
